export const links = [
  ["Accordion", "/components/accordion"],
  ["Button", "/components/button"],
  ["Calendar", "/components/calendar"],
  ["Card", "/components/card"],
  ["Cart Button", "/components/cart-button"],
  ["Checkbox", "/components/checkbox"],
  ["Discount Price", "/components/discount-price"],
  ["Form", "/components/form"],
  ["Grid Cards", "/components/grid-cards"],
  ["List", "/components/list"],
  ["Modal", "/components/modal"],
  ["NavigationBar", "/components/navigation-bar"],
  ["NavigationBarDropdown", "/components/navigation-bar-dropdown"],
  ["Product Card", "/components/product-card"],
  ["SearchBar", "/components/search-bar"],
  ["Spinner", "/components/spinner"],
  ["Star Rating", "/components/star-rating"],
  ["Switch", "/components/switch"],
  ["Testimonials", "/components/testimonials"],
  ["Toast", "/components/toast"],
  ["Tooltip", "/components/tooltip"],
  ["User", "/components/user"],
];
